/** Site-wide links and product metadata. Change here when repos move. */
export const site = {
  name: 'Astral',
  tagline: '通用组网与游戏联机',
  url: 'https://next.astral.fan',
  docsLegacy: 'https://astral.fan/',
  aml: 'https://aml.astral.fan/',
  githubOrg: 'https://github.com/AstralNext',
  easytier: 'https://easytier.cn/',
} as const;

export const products = {
  general: {
    id: 'astral',
    name: 'Astral',
    label: '通用版',
    path: '/astral/',
    blurb: '配置可控的通用组网',
    ctaHome: '通用组网',
    downloadLabel: '下载通用版',
    releases: 'https://github.com/AstralNext/Astral/releases',
    releasesApi: 'https://api.github.com/repos/AstralNext/Astral/releases/latest',
    downloadsJson: '/downloads-astral.json',
    githubProxy: 'https://gh.astral.fan/',
    repo: 'https://github.com/AstralNext/Astral',
    accent: 'teal',
    logo: '/logos/astral-general.svg',
    logoDark: '/logos/astral-general-dark.svg',
    mark: '/logos/astral-general-mark.svg',
  },
  game: {
    id: 'game',
    name: 'Astral Game',
    label: '游戏版',
    path: '/game/',
    blurb: '开箱即用的游戏联机',
    ctaHome: '游戏联机',
    downloadLabel: '下载游戏版',
    releases: 'https://github.com/AstralNext/AstralGame/releases',
    releasesApi: 'https://api.github.com/repos/AstralNext/AstralGame/releases/latest',
    downloadsJson: '/downloads.json',
    githubProxy: 'https://gh.astral.fan/',
    repo: 'https://github.com/AstralNext/AstralGame',
    accent: 'amber',
    logo: '/logos/astral-game.svg',
    logoDark: '/logos/astral-game-dark.svg',
    mark: '/logos/astral-game-mark.svg',
  },
} as const;
